{% set name = "calculix" %}
{% set version = "2.15" %}
{% set sha256 = "bc7dba721935af51b60c1b5aa1529a420476fc6432a7bec5254f8dfabaeb8a34" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}_{{ version }}.tar.bz2
  url: http://www.dhondt.de/ccx_{{ version }}.src.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - mingw.patch  # [win]

build:
  number: 1003

requirements:
  build:
    - {{ compiler("c") }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler("fortran") }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - perl
    - llvm-openmp  # [osx]
  host:
    - libblas
    - arpack
    - spooles
    - llvm-openmp  # [osx]
  run:
    - arpack
    - llvm-openmp  # [osx]

test:
  commands:
    - test -f ${PREFIX}/bin/ccx  # [unix]
    - test -f %LIBRARY_PREFIX%\bin\ccx.exe  # [win]

about:
  home: http://www.dhondt.de/
  license: GPL 2
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 3D Structural Finite Element Program
  description: A Free Software Three-Dimensional Structural
               Finite Element Program
  doc_url: http://www.dhondt.de/ccx_{{ version }}.pdf
  dev_url: http://www.dhondt.de/

extra:
  recipe-maintainers:
    - looooo
