{% set name = "calculix" %}
{% set version = "2.17" %}
{% set sha256 = "ca708ad4aa729d9f84a9faba343c1bcc0b7cc84ed372616ebb55c8e6fa8f6e50" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}_{{ version }}.tar.bz2
  url: http://www.dhondt.de/ccx_{{ version }}.src.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - time.patch  # [win or osx]
    # - mingw.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler("fortran") }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - m2-make   # [win]
    - make      # [not win]
    - perl
    - llvm-openmp  # [osx]
  host:
    - libblas
    - liblapack
    - arpack
    - spooles
    - llvm-openmp  # [osx]
  run:
    - arpack
    - llvm-openmp  # [osx]

test:
  commands:
    - test -f ${PREFIX}/bin/ccx  # [unix]
    - test -f %LIBRARY_PREFIX%\bin\ccx.exe  # [win]

about:
  home: http://www.dhondt.de/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: 3D Structural Finite Element Program
  description: A Free Software Three-Dimensional Structural Finite Element Program
  doc_url: http://www.dhondt.de/ccx_{{ version }}.pdf
  dev_url: http://www.dhondt.de/

extra:
  recipe-maintainers:
    - looooo
