schema_version: 1

context:
  name: calculix
  version: 2.23
  sha256: 9c88385c10fb04f5dc6c4e98027a51bebdd8aee3920e05190d6c1dd08357d6e7

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: http://www.dhondt.de/ccx_${{ version }}.src.tar.bz2
  sha256: ${{ sha256 }}
  patches:
    - patches/avoid-ifport.patch
    - patches/fix-readnewmesh-return.patch
    - if: win or osx
      then: patches/mingw_time.patch

build:
  number: 2

requirements:
  build:
    - make
    - perl
    - if: unix
      then:
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
        - ${{ compiler("fortran") }}
    - if: win
      then:
        - ${{ compiler('m2w64_c') }}
        - ${{ stdlib('m2w64_c') }}
        - ${{ compiler('m2w64_fortran') }}
    - if: osx
      then:
        - llvm-openmp
  host:
    - libblas
    - liblapack
    - arpack
    - spooles
    - if: osx
      then:
        - llvm-openmp
  run:
    - arpack
    - if: osx
      then:
        - llvm-openmp

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/bin/ccx
      - if: win
        then: if not exist %LIBRARY_PREFIX%\bin\ccx.exe exit 1

about:
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: 3D Structural Finite Element Program
  description: A Free Software Three-Dimensional Structural Finite Element Program
  homepage: https://www.dhondt.de/
  repository: https://github.com/Dhondtguido/CalculiX
  documentation: https://www.dhondt.de/ccx_${{ version }}.pdf

extra:
  recipe-maintainers:
    - looooo
    - Krande
