appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 7l5xHKulgEZ63/G+3a1zR88i4mATLhiKazUXtVCJUDhvVHb6QYM3IMe9E3kMuuCluRpAoJpe3B3COp/cWRmpqbONQekvbKzp5K4IScxNXxLtMO4sujiWWGEgTgl4V6Q2PAQwdgcXOohRp+pCCpJXvdH5ZV7aKudqnurXdp+FbW+qgSYkIJD8lrwGGIQMccLNNLafBcHRLbP+AniVMyFpJIFw7CrV2LuNiGxqb3UZyb3Cu4Fu0heCaClheZiyUEUoEX+soRTvfs4fcTESGZLOoqxWVyHgJaq7cMsS/++A/3vEhPFOvGN1QHQtd/99vY8zHfrwEINq9J3/SnOOnVVMEDuKzwz0tc4AD7ItbFLvriw/Ou+ojBDuvla2YPByspc6seVc6FFh4V0BwW0jLfmf9MupbdfxrGQIsaSSCkIRyKqV5Pb0GLksAaEB3q9uWMRo/xq1dEiaE3IGRVZIksOKHuU9dN+4718m2AWpXVp3CVoNAIvWQOabOcmZ9RFUpq79Bm/1iCdfAFBxziqBdudaDj6GngBOTq71rHuCByNhYmOIeKT4XHjYYCUbMBRHiOsdukdfDJUpQTcg7vIkjREaNtmPRvy701/0ulu7VKG2JMeyGe2XVttz9fOW9jWfipuDezjUCr+z0jJlBr9ZkxXdFUUqQiTeMW2hXYvQIJbjkNY=}
